services:
  app:
    build:
        context: .docker/app
        dockerfile: Dockerfile    
    volumes:
      - .:/app

  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app

  php:
    build:
        context: .docker/php
        dockerfile: Dockerfile    
    volumes:
      - .:/app

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "sample_database"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    ports:
      - 3309:3306      

  composer:
    image: composer/composer
    command: install
    volumes: 
      - .:/data

volumes:
  mysqldata: {}      